"""empty message

Revision ID: 3f5269fecac0
Revises: 1f26f1bac041
Create Date: 2022-02-23 13:22:25.454482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f5269fecac0'
down_revision = '1f26f1bac041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('jointime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('email_captcha', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('email_captcha', 'captcha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_captcha', 'captcha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('email_captcha', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table('user')
    # ### end Alembic commands ###
